name: bookdir2pdf_build
channels:
  - defaults
dependencies:
  - python=3.7*
  - pip
  - opencv
  - pip:
    - PyPDF2
    - git+https://github.com/pennersr/pyfpdf.git@feat-pillow
    - Pillow
    - pyinstaller
