name: bookdir2pdf_build
channels:
  - defaults
dependencies:
  - python=3.7*
  - pip
  - opencv
  - Pillow
  - pip:
    - PyPDF2
    - git+https://github.com/nimaid/pyfpdf.git@fix-close-jpeg
    - pyinstaller